"""empty message

Revision ID: 5dd6683c0617
Revises: 79644ff78748
Create Date: 2024-08-11 17:56:54.115820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd6683c0617'
down_revision = '79644ff78748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shows', schema=None) as batch_op:
        batch_op.drop_constraint('Shows_venue_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('Shows_artist_id_fkey', type_='foreignkey')
        batch_op.drop_column('artist_id')
        batch_op.drop_column('venue_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('Shows_artist_id_fkey', 'Artist', ['artist_id'], ['id'])
        batch_op.create_foreign_key('Shows_venue_id_fkey', 'Venue', ['venue_id'], ['id'])

    # ### end Alembic commands ###
