"""empty message

Revision ID: 79644ff78748
Revises: 904b95662e40
Create Date: 2024-08-11 17:53:34.067533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79644ff78748'
down_revision = '904b95662e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('facebook_link',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=220),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('facebook_link',
               existing_type=sa.String(length=220),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
