"""empty message

Revision ID: 904b95662e40
Revises: 610e14d38059
Create Date: 2024-08-11 15:44:55.858662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904b95662e40'
down_revision = '610e14d38059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
