"""empty message

Revision ID: fedfd1e9cc88
Revises: 5dd6683c0617
Create Date: 2024-08-11 18:17:38.269145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fedfd1e9cc88'
down_revision = '5dd6683c0617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_image_link', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shows', schema=None) as batch_op:
        batch_op.drop_column('venue_image_link')

    # ### end Alembic commands ###
